WITH CTE AS (
    SELECT COUNT(*) AS COUNT_2021_ID
    FROM USER_INFO
    WHERE JOINED lIKE '2021%')

SELECT
    YEAR(SALES_DATE),
    MONTH(SALES_DATE),
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND((COUNT(DISTINCT USER_ID) / COUNT_2021_ID), 1) AS Ratio
FROM
    ONLINE_SALE, CTE
WHERE USER_ID IN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED lIKE '2021%')
GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY
    YEAR(SALES_DATE) ASC, MONTH(SALES_DATE) ASC;
